spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root

  sql:
    init:
      mode: always
      schema-locations: classpath:props/schema-prod.sql
      data-locations: classpath:props/data.sql