CREATE TABLE "PRODUCT" (
    PRODUCT_ID INT AUTO_INCREMENT NOT NULL,
    NAME VARCHAR(45) NOT NULL,
    COST DOUBLE PRECISION NOT NULL,
    CONSTRAINT PRODUCT_PKEY
        PRIMARY KEY (PRODUCT_ID)
);

CREATE TABLE "ORDER" (
    ORDER_ID INT AUTO_INCREMENT NOT NULL,
    DATE DATE NOT NULL,
    COST DOUBLE PRECISION NOT NULL,
    CONSTRAINT ORDER_PKEY
        PRIMARY KEY (ORDER_ID)
);

CREATE TABLE "ORDER_PRODUCT" (
    ORDER_ID INT NOT NULL,
    PRODUCT_ID INT NOT NULL,
    CONSTRAINT ORDER_PRODUCT_PKEY
        PRIMARY KEY (ORDER_ID, PRODUCT_ID),
    CONSTRAINT ORDER_FK
        FOREIGN KEY (ORDER_ID)
            REFERENCES "ORDER" (ORDER_ID)
            ON UPDATE CASCADE
            ON DELETE CASCADE,
    CONSTRAINT PRODUCT_FK
        FOREIGN KEY (PRODUCT_ID)
            REFERENCES "PRODUCT" (PRODUCT_ID)
            ON UPDATE CASCADE
            ON DELETE CASCADE
);